/// <reference types='cypress' />

describe('inputFormMain', () => {
    it('verifyInput', () => {
        cy.visit('/')
        cy.get('#wpforms-689-field_0')
            .type('test')
            .should('have.value', 'test')
        cy.get('#wpforms-689-field_1')
            .type('test@test.ru')
            .should('have.value', 'test@test.ru')
        cy.get('#wpforms-689-field_2')
            .type('test')
            .should('have.value', 'test')
    })
    it('verifyChekboxMain', () => {
        cy.visit('/')
        cy.get('[type="checkbox"]').check()
        cy.get('#wpforms-689-field_10_1').uncheck()
        cy.get('#wpforms-689-field_10_2').uncheck()
        cy.get('#wpforms-689-field_10_3').uncheck()
        cy.get('#wpforms-689-field_10_5').uncheck()
        cy.get('#wpforms-689-field_10_6').uncheck()
        cy.get('#wpforms-689-field_10_1').check()
        cy.get('#wpforms-689-field_10_2').check()
    })
    it('verifyDropdownMain', () => {
        cy.visit('/')
        cy.get('#wpforms-689-field_11')
            .trigger('click')
            .should('contain.text', 'выберите')
            .should('have.value', '5')
        cy.get('#wpforms-689-field_11')
            .select('меньше 10')
            .should('have.value', '2')
        cy.get('#wpforms-689-field_11')
            .select('больше 10')
            .should('have.value', '4')
        cy.get('#wpforms-689-field_11')
            .select('индивидуальный')
            .should('have.value', '3')
    })
    it('verifyInputContacts', () => {
        cy.visit('/?page_id=33')
        cy.get('#wpforms-689-field_0')
            .type('test')
            .should('have.value', 'test')
        cy.get('#wpforms-689-field_1')
            .type('test@test.ru')
            .should('have.value', 'test@test.ru')
        cy.get('#wpforms-689-field_2')
            .type('test')
            .should('have.value', 'test')
    })
    it('verifyChekboxContacts', () => {
        cy.visit('/?page_id=33')
        cy.get('[type="checkbox"]').check()
        cy.get('#wpforms-689-field_10_1').uncheck()
        cy.get('#wpforms-689-field_10_2').uncheck()
        cy.get('#wpforms-689-field_10_3').uncheck()
        cy.get('#wpforms-689-field_10_5').uncheck()
        cy.get('#wpforms-689-field_10_6').uncheck()
        cy.get('#wpforms-689-field_10_1').check()
        cy.get('#wpforms-689-field_10_2').check()
    })
    it('verifyDropdownContacts', () => {
        cy.visit('/?page_id=33')
        cy.get('#wpforms-689-field_11')
            .trigger('click')
            .should('contain.text', 'выберите')
            .should('have.value', '5')
        cy.get('#wpforms-689-field_11')
            .select('меньше 10')
            .should('have.value', '2')
        cy.get('#wpforms-689-field_11')
            .select('больше 10')
            .should('have.value', '4')
        cy.get('#wpforms-689-field_11')
            .select('индивидуальный')
            .should('have.value', '3')
    })
})